### ISSUE TITLE
Decimal Places for CO2 ppm values

### ISSUE THREAD

**Issue by ando-shah** [ando-shah/co2-oracle#1]
The CO2 ppm value should have anywhere from 2 to 10 decimal places. Exact number is TBD @nociza

**Comment by ando-shah** [comment]
Set to 10 decimal places as a starting point

**Comment by nociza** [comment]
Should I make a factory and randomize some output within that threshold every time you query?

**Comment by ando-shah** [comment]
2 decimal places
